### ISSUE TITLE
Costruzione query incrementale tramite highlights

### ISSUE THREAD

**Issue by gianluca-pepe** [obdasystems/sparqling#37]
### Idea di base 
Rendere l'interazione con il widget suggestions quanto più grafica e interattiva possibile, senza aver bisogno di vedere e interagire con il grafo dell'ontologia.

### Assunzioni di partenza
- Deve essere un nuovo tipo di renderer integrato in Grapholscape 
- Se la query è vuota quando si sceglie il navigatore incrementale, si deve permettere la selezione della classe di partenza da cui procedere per mostrare i possibili passi successivi
- Si deve quindi poter cambiare visualizzazione senza perdere la query costruita, come già avviene per Graphol-Lite e Floaty
- Il widget suggestions rimane usabile e a supporto
- Deve essere possibile un alto grado di interattività con cui poter:
  - visualizzare o nascondere gerarchie
  - espandere o collassare diverse occorrenze di una object property con diverse classi

**Comment by gianluca-pepe** [comment]
A seguito delle varie prove si è deciso di evitare totalmente la visualizzazione grafica dei suggerimenti che portava in ogni caso ad un'esplosione di nodi tutti occorrenti sullo stesso nodo della query, rendendo di fatto inutile la visualizzazione.

A questo punto in sparqling si ha la modalità "Full page" che non è altro che una visualizzazione del query graph a tutta pagina e che prevede la costruzione della query solo tramite il widget suggestions.

Al momento attivabile con un tasto sul widget sul query-graph, l'attivazione al momento inibisce il passaggio al renderer incrementale di Grapholscape ed è quindi una soluzione temporanea.

Da fare:
- [ ] Rendere la modalità "Full-page" attivabile solo all'inizio facendo scegliere l'utente e inibire poi il passaggio dalla modalità classica con ontology graph + suggestions a quella "Full-page" con solo suggestions e viceversa.
- [ ] Rendere possibile impostare programmaticamente una o l'altra modalità in base alle esigenze interne (monolith)

**Comment by giacomoronconiobda** [comment]
Questa si può chiudere @gianluca-pepe?

**Comment by gianluca-pepe** [comment]
Si, se mai ci saranno nuove idee la riprenderemo.
